/**
 * EDC REST API
 * EDC REST APIs - merged by OpenApiMerger
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, from, lastValueFrom } from 'rxjs';

import { ContractAgreement, expandArray } from '@think-it-labs/edc-connector-client';
import { QuerySpec } from '../models/edc-connector-entities'
import { environment } from 'src/environments/environment';


@Injectable({
  providedIn: 'root'
})
export class ContractAgreementService {

  private readonly BASE_URL = `${environment.runtime.managementApiUrl}${environment.runtime.service.contractAgreement.baseUrl}`;

  constructor(private http: HttpClient) {
  }

    /**
     * Gets all contract agreements according to a particular query
     * @param querySpec
     */
    public queryAllAgreements(querySpec?: QuerySpec): Observable<any> {
      return from(lastValueFrom(this.http.post<Array<ContractAgreement>>(
        `${this.BASE_URL}${environment.runtime.service.asset.getAll}`, querySpec
      )).then(results => {
        return expandArray(results, () => new ContractAgreement());
      }));
    }

}
