/**
 * EDC REST API
 * EDC REST APIs - merged by OpenApiMerger
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, from, lastValueFrom } from 'rxjs';

import { ContractAgreement, expandArray, JSON_LD_DEFAULT_CONTEXT } from '@think-it-labs/edc-connector-client';
import { QuerySpec } from '../models/edc-connector-entities'
import { environment } from 'src/environments/environment';


@Injectable({
  providedIn: 'root'
})
export class ContractAgreementService {

  private readonly BASE_URL = `${environment.runtime.managementApiUrl}${environment.runtime.service.contractAgreement.baseUrl}`;

  constructor(private http: HttpClient) {
  }

  /**
   * Gets all contract agreements according to a particular query
   * @param querySpec
   */
  public queryAllAgreements(querySpec?: QuerySpec): Observable<any> {
    let body;

    if (querySpec) {
      body = {
        ...querySpec,
        "@context": JSON_LD_DEFAULT_CONTEXT,
      }
    }

    return from(lastValueFrom(this.http.post<Array<ContractAgreement>>(
      `${this.BASE_URL}${environment.runtime.service.asset.getAll}`, body
    )).then(results => {
      return expandArray(results, () => new ContractAgreement());
    }));
  }

  /**
 * Gets the total number of contract agreements
 */
  public count(): Observable<number> {
    return from(lastValueFrom(this.http.get<number>(
      `${environment.runtime.managementApiUrl}${environment.runtime.service.contractAgreement.count}`
    )));
  }

}
