/**
 * EDC REST API
 * EDC REST APIs - merged by OpenApiMerger
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

import { Vocabulary } from "../models/vocabulary";
import { environment } from "src/environments/environment";
import { JSON_LD_DEFAULT_CONTEXT } from '@think-it-labs/edc-connector-client';

@Injectable({
  providedIn: 'root'
})
export class VocabularyService {

  private readonly BASE_URL = `${environment.runtime.sharedUrl}${environment.runtime.service.vocabulary.baseUrl}`;
  private readonly PARTICIPANT_ID = `${environment.runtime.participantId}`;

  constructor(private http: HttpClient) {
  }

  /**
   * Gets all vocabularies according to the connector Id
   */
  public requestVocabularies(): Observable<Array<Vocabulary>> {

      const body = {
        "@context": JSON_LD_DEFAULT_CONTEXT,
        "connectorId": this.PARTICIPANT_ID
      }

    return this.http.post<Array<Vocabulary>>(
      `${this.BASE_URL}${environment.runtime.service.vocabulary.getAll}`, body
    );
  }
}
