/**
 * EDC REST API
 * EDC REST APIs - merged by OpenApiMerger
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

import { Vocabulary } from "../models/vocabulary";
import { environment } from "src/environments/environment";

@Injectable({
  providedIn: 'root'
})
export class VocabularyService {

  private readonly BASE_URL = `${environment.runtime.managementApiUrl}${environment.runtime.service.vocabulary.baseUrl}`;

  constructor(private http: HttpClient) {
  }

  /**
   * Gets all vocabularies according to a particular query
   */
  public requestVocabularies(): Observable<Array<Vocabulary>> {
    return this.http.post<Array<Vocabulary>>(
      `${this.BASE_URL}${environment.runtime.service.vocabulary.getAll}`, null
    );
  }
}
